version: "3.9"

x-server-context: &server-context
  build:
    context: .
    dockerfile: ./dockerfile
    args:
      APP_DIR: /var/duolingo
      APP_SRC: /var/duolingo/src

x-server-volume: &server-volume
  ./:/var/duolingo/

services:
  campaign-db:
    image: mongo:8.0.4
    container_name: campaign-db
    command: ["--wiredTigerCacheSizeGB", "1.5"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@1234
    ports:
      - 27077:27017
    networks:
      - duolingo
    volumes:
      - campaign-db:/data/db

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - duolingo
  
  message-queue:
    image: rabbitmq:3-management
    container_name: message-queue
    hostname: message-queue # Explicitly set the hostname
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root@1234
    volumes:
      - message-queue-data:/var/lib/rabbitmq
    networks:
      - duolingo

  message-api:
    <<: *server-context
    container_name: message-api
    depends_on:
      - message-queue
    environment:
      SERVICE_SRC: /var/duolingo/src/message-api
    ports:
      - 80:80
    networks:
      - duolingo
    volumes:
      - *server-volume 

networks:
  duolingo:
    driver: bridge

volumes:
  campaign-db:
  redis-data:
  message-queue-data:
