// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: lib/log/grpc_service/proto/logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          []byte                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStreamRequest) Reset() {
	*x = PushStreamRequest{}
	mi := &file_lib_log_grpc_service_proto_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStreamRequest) ProtoMessage() {}

func (x *PushStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_log_grpc_service_proto_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStreamRequest.ProtoReflect.Descriptor instead.
func (*PushStreamRequest) Descriptor() ([]byte, []int) {
	return file_lib_log_grpc_service_proto_logger_proto_rawDescGZIP(), []int{0}
}

func (x *PushStreamRequest) GetLine() []byte {
	if x != nil {
		return x.Line
	}
	return nil
}

type PushStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStreamResponse) Reset() {
	*x = PushStreamResponse{}
	mi := &file_lib_log_grpc_service_proto_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStreamResponse) ProtoMessage() {}

func (x *PushStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_log_grpc_service_proto_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStreamResponse.ProtoReflect.Descriptor instead.
func (*PushStreamResponse) Descriptor() ([]byte, []int) {
	return file_lib_log_grpc_service_proto_logger_proto_rawDescGZIP(), []int{1}
}

var File_lib_log_grpc_service_proto_logger_proto protoreflect.FileDescriptor

const file_lib_log_grpc_service_proto_logger_proto_rawDesc = "" +
	"\n" +
	"'lib/log/grpc_service/proto/logger.proto\x12\x06logger\"'\n" +
	"\x11PushStreamRequest\x12\x12\n" +
	"\x04line\x18\x01 \x01(\fR\x04line\"\x14\n" +
	"\x12PushStreamResponse2Q\n" +
	"\x06Logger\x12G\n" +
	"\n" +
	"PushStream\x12\x19.logger.PushStreamRequest\x1a\x1a.logger.PushStreamResponse\"\x00(\x01B\x11Z\x0f./logger;loggerb\x06proto3"

var (
	file_lib_log_grpc_service_proto_logger_proto_rawDescOnce sync.Once
	file_lib_log_grpc_service_proto_logger_proto_rawDescData []byte
)

func file_lib_log_grpc_service_proto_logger_proto_rawDescGZIP() []byte {
	file_lib_log_grpc_service_proto_logger_proto_rawDescOnce.Do(func() {
		file_lib_log_grpc_service_proto_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_log_grpc_service_proto_logger_proto_rawDesc), len(file_lib_log_grpc_service_proto_logger_proto_rawDesc)))
	})
	return file_lib_log_grpc_service_proto_logger_proto_rawDescData
}

var file_lib_log_grpc_service_proto_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_log_grpc_service_proto_logger_proto_goTypes = []any{
	(*PushStreamRequest)(nil),  // 0: logger.PushStreamRequest
	(*PushStreamResponse)(nil), // 1: logger.PushStreamResponse
}
var file_lib_log_grpc_service_proto_logger_proto_depIdxs = []int32{
	0, // 0: logger.Logger.PushStream:input_type -> logger.PushStreamRequest
	1, // 1: logger.Logger.PushStream:output_type -> logger.PushStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_log_grpc_service_proto_logger_proto_init() }
func file_lib_log_grpc_service_proto_logger_proto_init() {
	if File_lib_log_grpc_service_proto_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_log_grpc_service_proto_logger_proto_rawDesc), len(file_lib_log_grpc_service_proto_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_log_grpc_service_proto_logger_proto_goTypes,
		DependencyIndexes: file_lib_log_grpc_service_proto_logger_proto_depIdxs,
		MessageInfos:      file_lib_log_grpc_service_proto_logger_proto_msgTypes,
	}.Build()
	File_lib_log_grpc_service_proto_logger_proto = out.File
	file_lib_log_grpc_service_proto_logger_proto_goTypes = nil
	file_lib_log_grpc_service_proto_logger_proto_depIdxs = nil
}
