apiVersion: apps/v1
kind: Deployment
metadata:
  name: duolingo-test
  labels: { app: duolingo-test }
spec:
  replicas: 1
  selector:
    matchLabels: { app: duolingo-test }
  template:
    metadata:
      labels: { app: duolingo-test }
    spec:
      volumes:
        - name: app-configs
          configMap: { name: app-configs }
        - name: app-secrets
          secret: { secretName: app-secrets }
      containers:
        - name: duolingo-test
          image: duolingo-test:latest
          imagePullPolicy: Never
          command: ["go", "test", "./test/...", "-v"]
          restartPolicy: Never
          resources:
            requests: { cpu: "0.5", memory: "1Gi" }
            limits: { cpu: "0.5", memory: "1Gi" }
          env:
            - name: DUOLINGO_CONFIG_DIR_PATH
              value: /etc/duolingo/configs
          volumeMounts:
            - name: app-configs
              mountPath: /etc/duolingo/configs
            - name: app-secrets
              mountPath: /etc/duolingo/configs/secrets

