apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels: { app: mongodb }
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongodb }
  template:
    metadata:
      labels: { app: mongodb }
    spec:
      volumes:
      - name: mongodb-data
        emptyDir: { sizeLimit: 3Gi }
      containers:
      - name: mongodb
        image: mongo:8.0.4
        resources:
          requests: { cpu: "0.5", memory: "1Gi" }
          limits:   { cpu: "0.5", memory: "1Gi" }
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
        args: ["--bind_ip_all"]
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: { secretKeyRef: { name: app-secrets, key: mongodb.username }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: { secretKeyRef: { name: app-secrets, key: mongodb.password }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector: { app: mongodb }
  ports:
    - port: 27017
      targetPort: 27017
