# FROM golang:1.23

# ARG SERVICE_MAIN=""
# ENV APP_DIR=/var/duolingo
# ENV APP_SRC=/var/duolingo/src

# RUN apt-get update && \
#     apt-get install -y vim

# WORKDIR ${APP_SRC}

# COPY ../src/go.mod ../src/go.sum ./

# RUN go mod download

# COPY ../ ${APP_DIR}

# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ${APP_SRC}/server ${SERVICE_MAIN}

# RUN chmod +x ${APP_SRC}/server

# ENTRYPOINT ["sh", "-c", "${APP_SRC}/server"]
