version: "3.9"

services:
  campaign-db:
    image: mongo:8.0.4
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
          cpus: '0.50'
        reservations:
          memory: 500M
    command: ["--wiredTigerCacheSizeGB", "1.5"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@1234
    ports:
      - "27017:27017"
    networks:
      - duolingo
    volumes:
      - duolingo-campaign-db:/data/db

  redis:
    image: redis:7.4.2-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: '0.50'
        reservations:
          memory: 500M
    ports:
      - "6379:6379"
    volumes:
      - duolingo-redis-data:/data
    networks:
      - duolingo

  message-queue:
    image: rabbitmq:3-management
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: '0.50'
        reservations:
          memory: 500M
    hostname: message-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root@1234
    volumes:
      - duolingo-mq-data:/var/lib/rabbitmq
    networks:
      - duolingo

  input-message-api:
    image: duolingo-service:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: '0.50'
        reservations:
          memory: 500M
    command: service/input_message_api/server/serve_api.go
    environment:
      - CONTAINER_DNS_NAME={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
    ports:
      - "8001:8001"
    networks:
      - duolingo
    volumes:
      - ../:/var/duolingo/

  noti-builder:
    image: duolingo-service:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 500M
    command: service/noti_builder/server/run_builder.go
    environment:
      - CONTAINER_DNS_NAME={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
    networks:
      - duolingo
    volumes:
      - ../:/var/duolingo/
  
  push-noti-sender:
    image: duolingo-service:latest
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 500M
    command: service/push_noti_sender/server/sender.go
    environment:
      - CONTAINER_DNS_NAME={{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}
    networks:
      - duolingo
    volumes:
      - ../:/var/duolingo/

  log-service:
    image: duolingo-service:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 500M
    command: service/log_service/server/run_log_server.go
    networks:
      - duolingo
    ports:
      - "8002:8002"
    volumes:
      - ../:/var/duolingo/

networks:
  duolingo:
    driver: overlay

volumes:
  duolingo-campaign-db:
  duolingo-redis-data:
  duolingo-mq-data:
